on:
  pull_request:
    branches: "*"

permissions: write-all
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MAX_LINES_PR: ${{ secrets.MAX_LINES_PR || 600 }}
  PR_COMMENTS_URL: ${{ github.event.pull_request.comments_url }}
  PR_ADDITIONS: ${{ github.event.pull_request.additions }}
  PR_DELETIONS: ${{ github.event.pull_request.deletions }}
  PR_DESTINATION_BRANCH: ${{ github.event.pull_request.base.ref }}
jobs:
  check_pr_size:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Obtain the total number of modified lines of the lock files
        run: |
          chmod +x scripts/lines-of-lock.sh

          PR_MODIFY_LOCK=$(scripts/lines-of-lock.sh)
          PR_MODIFY_LOCK=$(PR_MODIFY_LOCK:-0)

          echo "PR_MODIFY_LOCK=${PR_MODIFY_LOCK}" >> $GITHUB_ENV

      - name: Obtaining missing data for reporting purposes
        run: |
          PR_MODIFY_ALL=$(($PR_ADDITIONS + $PR_DELETIONS))
          PR_MODIFY_REST=$(($PR_MODIFY_ALL - $PR_MODIFY_LOCK))

          if [ $PR_MODIFY_REST -gt $MAX_LINES_PR ]; then
              PR_EXTRA=$(($PR_MODIFY_REST - $MAX_LINES_PR))
          else
              PR_EXTRA=0
          fi

          echo "PR_MODIFY_ALL=${PR_MODIFY_ALL}" >> $GITHUB_ENV
          echo "PR_MODIFY_REST=${PR_MODIFY_REST}" >> $GITHUB_ENV
          echo "PR_EXTRA=${PR_EXTRA}" >> $GITHUB_ENV

      - name: Generate the message for commenting on the pr
        run: |
          if [[ $PR_MODIFY_REST -gt $MAX_LINES_PR ]]; then
            NOTE="@${{ github.actor }} Ups, tu pull request tiene mas de $MAX_LINES_PR lineas modificadas, tienes un total de $PR_MODIFY_REST, considera dividir este pull request."
          else
            NOTE="Perfecto, el pull request no sobrepasa las $MAX_LINES_PR lineas modificadas."
          fi

          MESSAGE=$(sed -e ':a;N;$!ba;s/\n/\\n/g'\
              -e "s/NOTE/$NOTE/" \
              -e "s/PR_ADDITIONS/$PR_ADDITIONS/" \
              -e "s/PR_DELETIONS/$PR_DELETIONS/" \
              -e "s/PR_MODIFY_ALL/$PR_MODIFY_ALL/" \
              -e "s/PR_MODIFY_LOCK/$PR_MODIFY_LOCK/" \
              -e "s/PR_MODIFY_REST/$PR_MODIFY_REST/" \
              -e "s/PR_EXTRA/$PR_EXTRA/" templates/pr-report.md)

          echo "MESSAGE=${MESSAGE}" >> $GITHUB_ENV

      - name: Remove previous reports from comments
        run: |
          COMMENTS=$(curl -L \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              $PR_COMMENTS_URL | jq '.[] | select(.body | contains("Resultados de la pre-revisión del PR"))')
              
          COMMENTS_ID=$(echo "$COMMENTS" | jq -r '.id')

          IFS=$'\n'
          for ID in $COMMENTS_ID; do
              
              COMMENT_URL="${{ github.api_url }}/repos/${{ github.repository }}/issues/comments/$ID"

              curl -L \
                  -X DELETE \
                  -H "Accept: application/vnd.github+json" \
                  -H "Authorization: token $GITHUB_TOKEN" \
                  -H "X-GitHub-Api-Version: 2022-11-28" \
                  $COMMENT_URL
          done

      - name: Shows the report as a comment in the pr
        run: |
          curl \
          -X POST \
          $PR_COMMENTS_URL \
          -H "Content-Type: application/json" \
          -H "Authorization: token $GITHUB_TOKEN" \
          --data "{ \"body\": \"$MESSAGE\" }"

      - name: Stop the execution of the workflow if the limit of modified lines is exceeded.
        run: |
          if [[ $PR_MODIFY_REST -gt $MAX_LINES_PR ]]
          then
              echo "Warning - total lines changed is greater than" $MAX_LINES_PR.
              echo "Please consider breaking this PR down."
              exit 1
          fi
